from enum import Enum


class Mutation(Enum):

    """
    Represents a mutation in the game, and assists parsing what mutations the player has from websocket data.
    """

    ACUTE_VISION_MUTATION = 1
    ANTENNAE_MUTATION = 2
    BEAK_MUTATION = 3
    BIG_WINGS_MUTATION = 4
    BLINK_MUTATION = 5
    CAMOUFLAGE_MUTATION = 6
    CLARITY_MUTATION = 7
    CLAWS_MUTATION = 8
    COLD_RESISTANCE_MUTATION = 9
    ELECTRICITY_RESISTANCE_MUTATION = 10
    EVOLUTION_MUTATION = 11
    FANGS_MUTATION = 12
    FIRE_RESISTANCE_MUTATION = 13
    HIGH_MP_MUTATION = 14
    HOOVES_MUTATION = 15
    HORNS_MUTATION = 16
    ICY_BLUE_SCALES_MUTATION = 17
    IMPROVED_ATTRIBUTES_MUTATION = 18
    IRIDESCENT_SCALES_MUTATION = 19
    LARGE_BONE_PLATES_MUTATION = 20
    MAGIC_RESISTANCE_MUTATION = 21
    MOLTEN_SCALES_MUTATION = 22
    MUTATION_RESISTANCE_MUTATION = 23
    PASSIVE_MAPPING_MUTATION = 24
    POISON_BREATH_MUTATION = 25
    POISON_RESISTANCE_MUTATION = 26
    REGENERATION_MUTATION = 27
    REPULSION_FIELD_MUTATION = 28
    ROBUST_MUTATION = 29
    RUGGED_BROWN_SCALES_MUTATION = 30
    SHAGGY_FUR_MUTATION = 31
    SLIMY_GREEN_SCALES_MUTATION = 32
    STINGER_MUTATION = 33
    STRONG_LEGS_MUTATION = 34
    TALONS_MUTATION = 35
    TENTACLE_SPIKE_MUTATION = 36
    THIN_METALLIC_SCALES_MUTATION = 37
    THIN_SKELETAL_STRUCTURE_MUTATION = 38
    TOUGH_SKIN_MUTATION = 39
    WILD_MAGIC_MUTATION = 40
    YELLOW_SCALES_MUTATION = 41























