;;; This file contains all of the general pddl facts
;;; that do not differ between game states

;;; gods
(god ashenzari)
(god beogh)
(god cheibriados)
(god dithmenos)
(god elyvilon)
(god fedhas)
(god gozag)
(god hepliaklqana)
(god jiyva)
(god kikubaaqudgha)
(god lugonu)
(god makhleb)
(god nemelex)
(god okawaru)
(god qazlal)
(god ru)
(god sif)
(god trog)
(god uskayaw)
(god vehumet)
(god wu_jian)
(god xom)
(god yredelemnul)
(god zin)
(god shining_one)

; used for unknown altars
(god unknown)

;;; potions
(potion ambrosia)
(potion berserkrage)
(potion brilliance)
(potion cancellation)
(potion curing)
(potion degeneration)
(potion experience)
(potion flight)
(potion haste)
(potion healwounds)
(potion invisibility)
(potion lignification)
(potion magic)
(potion might)
(potion mutation)
(potion resistance)
(potion stabbing)

;;; scrolls
(scroll acquirement)
(scroll amnesia)
(scroll blinking)
(scroll brandweapon)
(scroll enchantarmour)
(scroll enchantweapon)
(scroll fear)
(scroll fog)
(scroll holyword)
(scroll identity)
(scroll immolation)
(scroll magicmapping)
(scroll noise)
(scroll randomuselessness)
(scroll removecurse)
(scroll silence)
(scroll summoning)
(scroll teleportation)
(scroll torment)
(scroll vulnerability)

;;; spells
(non_target_based_spell alistairs_intoxication)
(non_target_based_spell animate_dead)
(non_target_based_spell animate_skeleton)
(non_target_based_spell aura_of_abjuration)
(non_target_based_spell beastly_appendage)
(non_target_based_spell blade_hands)
(non_target_based_spell blink)
(non_target_based_spell borgnjors_revivification)
(non_target_based_spell call_canine_familiar)
(non_target_based_spell call_imp)
(non_target_based_spell chain_lightning)
(non_target_based_spell confusing_touch)
(non_target_based_spell conjure_ball_lightning)
(non_target_based_spell conjure_flame)
(non_target_based_spell controlled_blink)
(non_target_based_spell corpse_rot)
(non_target_based_spell death_channel)
(non_target_based_spell deaths_door)
(non_target_based_spell discord)
(non_target_based_spell disjunction)
(non_target_based_spell dragon_form)
(non_target_based_spell dragons_call)
(non_target_based_spell eringyas_noxious_bog)
(non_target_based_spell excruciating_wounds)
(non_target_based_spell foxfire)
(non_target_based_spell hydra_form)
(non_target_based_spell ice_form)
(non_target_based_spell ignite_poison)
(non_target_based_spell ignition)
(non_target_based_spell infusion)
(non_target_based_spell iskenderuns_battlesphere)
(non_target_based_spell ledas_liquefaction)
(non_target_based_spell malign_gateway)
(non_target_based_spell metabolic_englaciation)
(non_target_based_spell monstrous_menagerie)
(non_target_based_spell necromutation)
(non_target_based_spell olgrebs_toxic_radiance)
(non_target_based_spell ozocubus_armour)
(non_target_based_spell ozocubus_refrigeration)
(non_target_based_spell portal_projectile)
(non_target_based_spell recall)
(non_target_based_spell ring_of_flames)
(non_target_based_spell shadow_creatures)
(non_target_based_spell shatter)
(non_target_based_spell shroud_of_golubria)
(non_target_based_spell silence)
(non_target_based_spell simulacrum)
(non_target_based_spell song_of_slaying)
(non_target_based_spell spectral_weapon)
(non_target_based_spell spellforged_servitor)
(non_target_based_spell spider_form)
(non_target_based_spell statue_form)
(non_target_based_spell sticks_to_snakes)
(non_target_based_spell sublimation_of_blood)
(non_target_based_spell summon_demon)
(non_target_based_spell summon_forest)
(non_target_based_spell summon_greater_demon)
(non_target_based_spell summon_guardian_golem)
(non_target_based_spell summon_horrible_things)
(non_target_based_spell summon_hydra)
(non_target_based_spell summon_ice_beast)
(non_target_based_spell summon_mana_viper)
(non_target_based_spell summon_small_mammal)
(non_target_based_spell swiftness)
(target_based_spell absolute_zero)
(target_based_spell agony)
(target_based_spell airstrike)
(target_based_spell apportation)
(target_based_spell bolt_of_magma)
(target_based_spell borgnjors_vile_clutch)
(target_based_spell cause_fear)
(target_based_spell corona)
(target_based_spell dazzling_flash)
(target_based_spell dispel_undead)
(target_based_spell dispersal)
(target_based_spell ensorcelled_hibernation)
(target_based_spell fire_storm)
(target_based_spell fireball)
(target_based_spell freeze)
(target_based_spell freezing_cloud)
(target_based_spell frozen_ramparts)
(target_based_spell fulminant_prism)
(target_based_spell gells_gravitas)
(target_based_spell hailstorm)
(target_based_spell haunt)
(target_based_spell infestation)
(target_based_spell inner_flame)
(target_based_spell invisibility)
(target_based_spell iron_shot)
(target_based_spell irradiate)
(target_based_spell iskenderuns_mystic_blast)
(target_based_spell lees_rapid_deconstruction)
(target_based_spell lehudibs_crystal_spear)
(target_based_spell lesser_beckoning)
(target_based_spell lightning_bolt)
(target_based_spell magic_dart)
(target_based_spell mephitic_cloud)
(target_based_spell orb_of_destruction)
(target_based_spell pain)
(target_based_spell passage_of_golubria)
(target_based_spell passwall)
(target_based_spell petrify)
(target_based_spell poisonous_vapours)
(target_based_spell sandblast)
(target_based_spell searing_ray)
(target_based_spell shock)
(target_based_spell slow)
(target_based_spell starburst)
(target_based_spell static_discharge)
(target_based_spell sticky_flame)
(target_based_spell sting)
(target_based_spell stone_arrow)
(target_based_spell summon_lightning_spire)
(target_based_spell teleport_other)
(target_based_spell tornado)
(target_based_spell tukimas_dance)
(target_based_spell vampiric_draining)
(target_based_spell yaras_violent_unravelling)

;;; skills
(skill fighting)
(skill long_blades)
(skill short_blades)
(skill axes)
(skill maces_&_flails)
(skill polearms)
(skill staves)
(skill unarmed_combat)
(skill bows)
(skill crossbows)
(skill throwing)
(skill slings)
(skill armour)
(skill dodging)
(skill shields)
(skill spellcasting)
(skill conjurations)
(skill hexes)
(skill charms)
(skill summonings)
(skill necromancy)
(skill translocations)
(skill transmutation)
(skill fire_magic)
(skill ice_magic)
(skill air_magic)
(skill earth_magic)
(skill poison_magic)
(skill invocations)
(skill evocations)
(skill stealth)

;;; abilities
(non_target_ability apocalypse)
(non_target_ability banish_self)
(non_target_ability bat_form)
(non_target_ability bend_space)
(non_target_ability bend_time)
(non_target_ability berserk)
(non_target_ability blink)
(non_target_ability briar_patch)
(non_target_ability bribe_branch)
(non_target_ability brothers_in_arms)
(non_target_ability call_merchant)
(non_target_ability channel_magic)
(non_target_ability cleansing_flame)
(non_target_ability corrupt)
(non_target_ability cure_bad_mutations)
(non_target_ability depart_abyss)
(non_target_ability disaster_area)
(non_target_ability divine_protection)
(non_target_ability divine_shield)
(non_target_ability divine_vigour)
(non_target_ability drain_life)
(non_target_ability draw_out_power)
(non_target_ability elemental_force)
(non_target_ability finesse)
(non_target_ability flight)
(non_target_ability gain_random_mutations)
(non_target_ability greater_healing)
(non_target_ability grow_ballistomycete)
(non_target_ability grow_oklob_plant)
(non_target_ability heal_wounds)
(non_target_ability heavenly_storm)
(non_target_ability heroism)
(non_target_ability idealise)
(non_target_ability lesser_healing)
(non_target_ability purification)
(non_target_ability recall)
(non_target_ability recall_undead_slaves)
(non_target_ability receive_corpses)
(non_target_ability receive_necronomicon)
(non_target_ability recite)
(non_target_ability request_jelly)
(non_target_ability resurrection)
(non_target_ability sanctuary)
(non_target_ability scrying)
(non_target_ability serpents_lash)
(non_target_ability shadow_form)
(non_target_ability slimify)
(non_target_ability slouch)
(non_target_ability step_from_time)
(non_target_ability stomp)
(non_target_ability summon_divine_warrior)
(non_target_ability summon_greater_servant)
(non_target_ability summon_lesser_servant)
(non_target_ability temporal_distortion)
(non_target_ability toggle_divine_energy)
(non_target_ability toggle_injury_mirror)
(non_target_ability torment)
(non_target_ability trogs_hand)
(non_target_ability vitalisation)
(non_target_ability wall_jump)
(target_ability_location animate_dead)
(target_ability_location animate_remains)
(target_ability_location banish)
(target_ability_location controlled_blink)
(target_ability_location enslave_soul)
(target_ability_location give_item_to_follower)
(target_ability_location grand_finale)
(target_ability_location heal_other)
(target_ability_location hop)
(target_ability_location Imprison)
(target_ability_location line_pass)
(target_ability_location major_destruction)
(target_ability_location minor_destruction)
(target_ability_location overgrow)
(target_ability_location power_leap)
(target_ability_location rolling_charge)
(target_ability_location shadow_step)
(target_ability_location smite)
(target_ability_location spit_poison)
(target_ability_location transference)
(target_ability_location upheaval)
(target_ability_menu ancestor_identity)
(target_ability_menu ancestor_life)
(target_ability_menu brand_weapon_with_holy)
(target_ability_menu brand_weapon_with_pain)
(target_ability_menu corrupt_weapon)
(target_ability_menu curse_item)
(target_ability_menu deal_four)
(target_ability_menu forget_spell)
(target_ability_menu pick_a_card_any_card)
(target_ability_menu stack_five)
(target_ability_menu transfer_knowledge)
(target_ability_menu triple_draw)
(target_ability_text_message potion_petition)

;;; dungeon locations
(place dungeon_1)
(place dungeon_2)
(place dungeon_3)
(place dungeon_4)
(place dungeon_5)
(place dungeon_6)
(place dungeon_7)
(place dungeon_8)
(place dungeon_9)
(place dungeon_10)
(place dungeon_11)
(place dungeon_12)
(place dungeon_13)
(place dungeon_14)
(place dungeon_15)

(place lair_1)
(place lair_2)
(place lair_3)
(place lair_4)
(place lair_5)
(place lair_6)

(place swamp_1)
(place swamp_2)
(place swamp_3)
(place swamp_4)

(place shoals_1)
(place shoals_2)
(place shoals_3)
(place shoals_4)

(place snake_pit_1)
(place snake_pit_2)
(place snake_pit_3)
(place snake_pit_4)

(place spiders_nest_1)
(place spiders_nest_2)
(place spiders_nest_3)
(place spiders_nest_4)

(place slime_pits_1)
(place slime_pits_2)
(place slime_pits_3)
(place slime_pits_4)
(place slime_pits_5)

(place orcish_mines_1)
(place orcish_mines_2)

(place elven_halls_1)
(place elven_halls_2)
(place elven_halls_3)

(place vaults_1)
(place vaults_2)
(place vaults_3)
(place vaults_4)
(place vaults_5)

(place crypt_1)
(place crypt_2)
(place crypt_3)

(place tomb_1)
(place tomb_2)
(place tomb_3)

(place depths_1)
(place depths_2)
(place depths_3)
(place depths_4)
(place depths_5)

(place abyss_1)
(place abyss_2)
(place abyss_3)
(place abyss_4)
(place abyss_5)

(place cocytus_1)
(place cocytus_2)
(place cocytus_3)
(place cocytus_4)
(place cocytus_5)
(place cocytus_6)
(place cocytus_7)

(place gehenna_1)
(place gehenna_2)
(place gehenna_3)
(place gehenna_4)
(place gehenna_5)
(place gehenna_6)
(place gehenna_7)

(place tartarus_1)
(place tartarus_2)
(place tartarus_3)
(place tartarus_4)
(place tartarus_5)
(place tartarus_6)
(place tartarus_7)

(place iron_city_of_dis_1)
(place iron_city_of_dis_2)
(place iron_city_of_dis_3)
(place iron_city_of_dis_4)
(place iron_city_of_dis_5)
(place iron_city_of_dis_6)
(place iron_city_of_dis_7)

(place zot_1)
(place zot_2)
(place zot_3)
(place zot_4)
(place zot_5)

(connected dungeon_1 dungeon_2)
(connected dungeon_2 dungeon_3)
(connected dungeon_3 dungeon_4)
(connected dungeon_4 dungeon_5)
(connected dungeon_5 dungeon_6)
(connected dungeon_6 dungeon_7)
(connected dungeon_7 dungeon_8)
(connected dungeon_8 dungeon_9)
(connected dungeon_9 dungeon_10)
(connected dungeon_10 dungeon11)
(connected dungeon_11 dungeon12)
(connected dungeon_12 dungeon13)
(connected dungeon_13 dungeon14)
(connected dungeon_14 dungeon15)

(connected lair_1 lair_2)
(connected lair_2 lair_3)
(connected lair_3 lair_4)
(connected lair_4 lair_5)
(connected lair_5 lair_6)

(connected swamp_1 swamp_2)
(connected swamp_2 swamp_3)
(connected swamp_3 swamp_4)

(connected shoals_1 shoals_2)
(connected shoals_2 shoals_3)
(connected shoals_3 shoals_4)

(connected snake_pit_1 snake_pit_2)
(connected snake_pit_2 snake_pit_3)
(connected snake_pit_3 snake_pit_4)

(connected spiders_nest_1 spiders_nest_2)
(connected spiders_nest_2 spiders_nest_3)
(connected spiders_nest_3 spiders_nest_4)

(connected slime_pits_1 slime_pits_2)
(connected slime_pits_2 slime_pits_3)
(connected slime_pits_3 slime_pits_4)
(connected slime_pits_4 slime_pits_5)

(connected orcish_mines_1 orcish_mines_2)

(connected elven_halls_1 elven_halls_2)
(connected elven_halls_2 elven_halls_3)

(connected vaults_1 vaults_2)
(connected vaults_2 vaults_3)
(connected vaults_3 vaults_4)
(connected vaults_4 vaults_5)

(connected crypt_1 crypt_2)
(connected crypt_2 crypt_3)

(connected tomb_1 tomb_2)
(connected tomb_2 tomb_3)

(connected depths_1 depths_2)
(connected depths_2 depths_3)
(connected depths_3 depths_4)
(connected depths_4 depths_5)

(connected abyss_1 abyss_2)
(connected abyss_2 abyss_3)
(connected abyss_3 abyss_4)
(connected abyss_4 abyss_5)

(connected cocytus_1 cocytus_2)
(connected cocytus_2 cocytus_3)
(connected cocytus_3 cocytus_4)
(connected cocytus_4 cocytus_5)
(connected cocytus_5 cocytus_6)
(connected cocytus_6 cocytus_7)

(connected gehenna_1 gehenna_2)
(connected gehenna_2 gehenna_3)
(connected gehenna_3 gehenna_4)
(connected gehenna_4 gehenna_5)
(connected gehenna_5 gehenna_6)
(connected gehenna_6 gehenna_7)

(connected tartarus_1 tartarus_2)
(connected tartarus_2 tartarus_3)
(connected tartarus_3 tartarus_4)
(connected tartarus_4 tartarus_5)
(connected tartarus_5 tartarus_6)
(connected tartarus_6 tartarus_7)

(connected iron_city_of_dis_1 iron_city_of_dis_2)
(connected iron_city_of_dis_2 iron_city_of_dis_3)
(connected iron_city_of_dis_3 iron_city_of_dis_4)
(connected iron_city_of_dis_4 iron_city_of_dis_5)
(connected iron_city_of_dis_5 iron_city_of_dis_6)
(connected iron_city_of_dis_6 iron_city_of_dis_7)

(connected zot_1 zot_2)
(connected zot_2 zot_3)
(connected zot_3 zot_4)
(connected zot_4 zot_5)
