;;; This file contains all of the general pddl facts
;;; that do not differ between game states

;;; replacement for lack of integers for FastDownward
(qualitative_quantity none)
(qualitative_quantity low)
(qualitative_quantity medium_low)
(qualitative_quantity medium)
(qualitative_quantity medium_high)
(qualitative_quantity high)
(qualitative_quantity maxed)

;;; runes
(rune serpentine_rune)
(rune decaying_rune)
(rune barnacled_rune)
(rune gossamer_rune)
(rune abyssal_rune)
(rune silver_rune)
(rune slimy_rune)
(rune dark_rune)
(rune glowing_rune)
(rune fiery_rune)
(rune magical_rune)
(rune demonic_rune)
(rune golden_rune)
(rune iron_rune)
(rune icy_rune)
(rune obsidian_rune)
(rune bone_rune)

;;; terrain types
(terrain shallow_water)
(terrain deep_water)
(terrain lava)
(terrain rock_wall)
(terrain translucent_rock_wall)
(terrain green_crystal_wall)
(terrain stone_wall)
(terrain translucent_stone_wall)
(terrain metal_wall)
(terrain unnaturally_hard_wall)
(terrain bush)
(terrain fungus)
(terrain plant)
(terrain trees)

;;; monster danger rating
(danger_rating easy)
(danger_rating dangerous)
(danger_rating very_dangerous)

;;; monster types
(monster abomination)
(monster acid_blob)
(monster acid_dragon)
(monster adder)
(monster agate_snail)
(monster agnes)
(monster air_elemental)
(monster aizul)
(monster alligator)
(monster alligator_snapping_turtle)
(monster anaconda)
(monster ancient_bear)
(monster ancient_champion)
(monster ancient_lich)
(monster ancient_zyme)
(monster angel)
(monster ant_larva)
(monster antaeus)
(monster anubis_guard)
(monster apis)
(monster apocalypse_crab)
(monster arachne)
(monster archer_statue)
(monster asmodeus)
(monster asterion)
(monster azrael)
(monster azure_jelly)
(monster baby_alligator)
(monster bai_suzhen)
(monster ball_lightning)
(monster ball_python)
(monster ballistomycete)
(monster ballistomycete_spore)
(monster balrug)
(monster barachi_(monster))
(monster basilisk)
(monster bat)
(monster battlesphere)
(monster bennu)
(monster big_fish)
(monster big_kobold)
(monster black_bear)
(monster black_draconian)
(monster black_mamba)
(monster black_sun)
(monster blink_frog)
(monster blizzard_demon)
(monster bloated_husk)
(monster block_of_ice)
(monster blood_saint)
(monster blork_the_orc)
(monster blue_death)
(monster blue_devil)
(monster bog_body)
(monster bog_mummy)
(monster boggart)
(monster bone_dragon)
(monster boring_beetle)
(monster boris)
(monster boulder_beetle)
(monster brain_worm)
(monster briar_patch)
(monster brimstone_fiend)
(monster brown_ooze)
(monster bullfrog)
(monster bumblebee)
(monster bunyip)
(monster burning_bush)
(monster bush)
(monster butterfly)
(monster cacodemon)
(monster cane_toad)
(monster catoblepas)
(monster caustic_shrike)
(monster centaur_(monster))
(monster centaur_warrior)
(monster cerebov)
(monster chaos_butterfly)
(monster chaos_champion)
(monster chaos_spawn)
(monster charred_statue)
(monster cherub)
(monster chimera)
(monster chuck)
(monster clay_golem)
(monster conjurer_statue)
(monster corrupter)
(monster crawling_corpse)
(monster crazy_yiuf)
(monster crimson_imp)
(monster crocodile)
(monster crystal_golem)
(monster crystal_guardian)
(monster curse_skull)
(monster curse_toe)
(monster cyclops)
(monster daeva)
(monster dancing_weapon)
(monster dart_slug)
(monster death_cob)
(monster death_drake)
(monster death_knight)
(monster death_ooze)
(monster death_scarab)
(monster death_yak)
(monster deathcap)
(monster deep_dwarf_(monster))
(monster deep_dwarf_artificer)
(monster deep_dwarf_berserker)
(monster deep_dwarf_death_knight)
(monster deep_dwarf_necromancer)
(monster deep_dwarf_scion)
(monster deep_elf_annihilator)
(monster deep_elf_archer)
(monster deep_elf_blademaster)
(monster deep_elf_conjurer)
(monster deep_elf_death_mage)
(monster deep_elf_demonologist)
(monster deep_elf_elementalist)
(monster deep_elf_fighter)
(monster deep_elf_high_priest)
(monster deep_elf_knight)
(monster deep_elf_mage)
(monster deep_elf_master_archer)
(monster deep_elf_priest)
(monster deep_elf_soldier)
(monster deep_elf_sorcerer)
(monster deep_elf_summoner)
(monster deep_troll)
(monster deep_troll_earth_mage)
(monster deep_troll_shaman)
(monster demigod_(monster))
(monster demon)
(monster demonic_crawler)
(monster demonic_monsters)
(monster demonspawn_(monster))
(monster derived_undead)
(monster diamond_obelisk)
(monster dire_elephant)
(monster dispater)
(monster dissolution)
(monster donald)
(monster doom_hound)
(monster dowan)
(monster draconian_(monster))
(monster draconian_annihilator)
(monster draconian_knight)
(monster draconian_monk)
(monster draconian_scorcher)
(monster draconian_shifter)
(monster draconian_stormcaller)
(monster draconian_zealot)
(monster dream_sheep)
(monster drowned_soul)
(monster dryad)
(monster duane)
(monster duvessa)
(monster dwarf)
(monster earth_elemental)
(monster edmund)
(monster efreet)
(monster eidolon)
(monster eldritch_tentacle)
(monster electric_eel)
(monster electric_golem)
(monster eleionoma)
(monster elemental_wellspring)
(monster elephant)
(monster elephant_slug)
(monster elf)
(monster emperor_scorpion)
(monster entropy_weaver)
(monster ereshkigal)
(monster erica)
(monster erolcha)
(monster ettin)
(monster eustachio)
(monster executioner)
(monster eye_of_devastation)
(monster eye_of_draining)
(monster fannar)
(monster faun)
(monster felid_(monster))
(monster fenstrider_witch)
(monster fire_bat)
(monster fire_crab)
(monster fire_dragon)
(monster fire_drake)
(monster fire_elemental)
(monster fire_giant)
(monster fire_vortex)
(monster firespitter_statue)
(monster flaming_corpse)
(monster flayed_ghost)
(monster floating_eye)
(monster flying_skull)
(monster formicid_(monster))
(monster formicid_drone)
(monster formicid_venom_mage)
(monster frances)
(monster francis)
(monster frederick)
(monster freezing_wraith)
(monster frilled_lizard)
(monster frost_giant)
(monster frost-covered_statue)
(monster fungus)
(monster gargoyle_(monster))
(monster gastronok)
(monster gelid_demonspawn)
(monster geryon)
(monster ghost_crab)
(monster ghost_moth)
(monster ghoul_(monster))
(monster giant_amoeba)
(monster giant_blowfly)
(monster giant_centipede)
(monster giant_cockroach)
(monster giant_firefly)
(monster giant_goldfish)
(monster giant_mite)
(monster giant_slug)
(monster giant_toad)
(monster gila_monster)
(monster gloorx_vloq)
(monster glowing_orange_brain)
(monster glowing_shapeshifter)
(monster gnoll_(monster))
(monster gnoll_sergeant)
(monster gnoll_shaman)
(monster goblin)
(monster golden_dragon)
(monster golden_eye)
(monster goliath_beetle)
(monster goliath_frog)
(monster grand_avatar_(monster))
(monster great_orb_of_eyes)
(monster green_death)
(monster green_draconian)
(monster grey_draconian)
(monster grey_rat)
(monster griffon)
(monster grinder)
(monster grizzly_bear)
(monster grum)
(monster guardian_golem)
(monster guardian_mummy)
(monster guardian_naga)
(monster guardian_serpent)
(monster hairy_devil)
(monster halazid_warlock)
(monster halfling_(monster))
(monster harold)
(monster harpy)
(monster hell_beast)
(monster hell_hog)
(monster hell_hound)
(monster hell_knight)
(monster hell_rat)
(monster hell_sentinel)
(monster hellephant)
(monster hellion)
(monster hellwing)
(monster hill_giant)
(monster hippogriff)
(monster hobgoblin)
(monster hog)
(monster holy_swine)
(monster hornet)
(monster hound)
(monster howler_monkey)
(monster human_(monster))
(monster hungry_ghost)
(monster hydra)
(monster ice_beast)
(monster ice_devil)
(monster ice_dragon)
(monster ice_fiend)
(monster ice_statue)
(monster ignacio)
(monster ignis)
(monster iguana)
(monster ijyb)
(monster ilsuiw)
(monster imperial_myrmidon)
(monster inept_mimic)
(monster infernal_demonspawn)
(monster insubstantial_wisp)
(monster iron_devil)
(monster iron_dragon)
(monster iron_elemental)
(monster iron_giant)
(monster iron_golem)
(monster iron_imp)
(monster iron_troll)
(monster ironbrand_convoker)
(monster ironheart_preserver)
(monster jackal)
(monster jelly)
(monster jellyfish)
(monster jessica)
(monster jiangshi)
(monster jorgrun)
(monster jory)
(monster joseph)
(monster josephine)
(monster jozef)
(monster juggernaut)
(monster jumping_spider)
(monster khufu)
(monster killer_bee)
(monster killer_bee_larva)
(monster killer_klown)
(monster kirke)
(monster kobold_(monster))
(monster kobold_demonologist)
(monster komodo_dragon)
(monster kraken)
(monster laboratory_rat)
(monster lamia)
(monster large_abomination)
(monster lasher_statue)
(monster lava_fish)
(monster lava_snake)
(monster lava_worm)
(monster lemure)
(monster leopard_gecko)
(monster lich)
(monster lightning_spire)
(monster lindwurm)
(monster list_of_monsters)
(monster lom_lobon)
(monster lorocyproca)
(monster lost_soul)
(monster louise)
(monster lurking_horror)
(monster macabre_mass)
(monster maggie)
(monster mana_viper)
(monster manticore)
(monster mara)
(monster margery)
(monster master_blaster)
(monster master_elementalist)
(monster maud)
(monster maurice)
(monster meliai)
(monster menkaure)
(monster mennas)
(monster merfolk)
(monster merfolk_(monster))
(monster merfolk_aquamancer)
(monster merfolk_avatar)
(monster merfolk_impaler)
(monster merfolk_javelineer)
(monster merfolk_siren)
(monster mermaid)
(monster metal_gargoyle)
(monster michael)
(monster midge)
(monster mimic_(monster))
(monster minotaur_(monster))
(monster mnoleg)
(monster molten_gargoyle)
(monster monster_attributes)
(monster monster_generation)
(monster monsters)
(monster monstrous_demonspawn)
(monster moth_of_suppression)
(monster moth_of_wrath)
(monster mottled_draconian)
(monster mottled_dragon)
(monster mummy_(monster))
(monster mummy_priest)
(monster murray)
(monster naga_(monster))
(monster naga_mage)
(monster naga_ritualist)
(monster naga_sharpshooter)
(monster naga_warrior)
(monster nagaraja)
(monster nameless_horror)
(monster natasha)
(monster necromancer_(monster))
(monster necrophage)
(monster nellie)
(monster neqoxec)
(monster nergalle)
(monster nessos)
(monster nikola)
(monster norbert)
(monster norris)
(monster obsidian_statue)
(monster octopode_(monster))
(monster octopode_crusher)
(monster ogre_(monster))
(monster ogre_mage)
(monster oklob_plant)
(monster oklob_sapling)
(monster ooze)
(monster ophan)
(monster orange_crystal_statue)
(monster orange_demon)
(monster orb_guardian)
(monster orb_of_fire)
(monster orb_spider)
(monster orc)
(monster orc_high_priest)
(monster orc_knight)
(monster orc_priest)
(monster orc_sorcerer)
(monster orc_warlord)
(monster orc_warrior)
(monster orc_wizard)
(monster paladin_(monster))
(monster pale_draconian)
(monster pan_(monster))
(monster pandemonium_lord)
(monster peacekeeper)
(monster pearl_dragon)
(monster phantasmal_warrior)
(monster phantom)
(monster phoenix)
(monster pikel)
(monster pillar_of_salt)
(monster pit_fiend)
(monster plague_shambler)
(monster plant)
(monster polar_bear)
(monster polymoth)
(monster polyphemus)
(monster porcupine)
(monster priests)
(monster prince_ribbit)
(monster profane_servitor)
(monster psyche)
(monster pulsating_lump)
(monster purgy)
(monster purple_draconian)
(monster putrid_demonspawn)
(monster quasit)
(monster queen_ant)
(monster queen_bee)
(monster quicksilver_dragon)
(monster quokka)
(monster ragged_hierophant)
(monster raiju)
(monster rakshasa)
(monster rat)
(monster raven)
(monster ravenous_mimic)
(monster reaper)
(monster red_devil)
(monster red_draconian)
(monster redback)
(monster revenant)
(monster rime_drake)
(monster river_rat)
(monster robin)
(monster rock_troll)
(monster rock_worm)
(monster rotting_devil)
(monster rotting_hulk)
(monster roxanne)
(monster royal_mummy)
(monster rupert)
(monster rust_devil)
(monster saint_roka)
(monster salamander)
(monster salamander_firebrand)
(monster salamander_mystic)
(monster salamander_stormcaller)
(monster saltling)
(monster satyr)
(monster scorpion)
(monster sea_snake)
(monster seraph)
(monster serpent_of_hell_(cocytus))
(monster serpent_of_hell_(dis))
(monster serpent_of_hell_(gehenna))
(monster serpent_of_hell_(tartarus))
(monster servant_of_whispers)
(monster shadow)
(monster shadow_demon)
(monster shadow_dragon)
(monster shadow_imp)
(monster shadow_wraith)
(monster shambling_mangrove)
(monster shapeshifter)
(monster shard_shrike)
(monster shark)
(monster shedu)
(monster sheep)
(monster shining_eye)
(monster shock_serpent)
(monster sigmund)
(monster silent_spectre)
(monster silver_star)
(monster silver_statue)
(monster simulacrum_(monster))
(monster sixfirhy)
(monster skeletal_warrior)
(monster skeleton_(monster))
(monster sky_beast)
(monster slave)
(monster slime_creature)
(monster small_abomination)
(monster smoke_demon)
(monster snail_statue)
(monster snaplasher_vine)
(monster snapping_turtle)
(monster snorg)
(monster sojobo)
(monster soldier_ant)
(monster sonja)
(monster soul_eater)
(monster spark_wasp)
(monster spatial_maelstrom)
(monster spatial_vortex)
(monster spectral_thing)
(monster spellforged_servitor_(monster))
(monster sphinx)
(monster spider)
(monster spiny_worm)
(monster spirit)
(monster spirit_wolf)
(monster spooky_statue)
(monster spriggan_(monster))
(monster spriggan_air_mage)
(monster spriggan_assassin)
(monster spriggan_berserker)
(monster spriggan_defender)
(monster spriggan_druid)
(monster spriggan_enchanter)
(monster spriggan_rider)
(monster starcursed_mass)
(monster steam_dragon)
(monster stone_giant)
(monster stone_golem)
(monster storm_dragon)
(monster subtractor_snake)
(monster sun_demon)
(monster swamp_dragon)
(monster swamp_drake)
(monster swamp_worm)
(monster tarantella)
(monster template:monster_info)
(monster tengu_(monster))
(monster tengu_conjurer)
(monster tengu_reaver)
(monster tengu_warrior)
(monster tentacled_monstrosity)
(monster tentacled_starspawn)
(monster terence)
(monster terpsichore)
(monster test_spawner)
(monster the_enchantress)
(monster the_iron_giant)
(monster the_lernaean_hydra)
(monster the_royal_jelly)
(monster thorn_hunter)
(monster thorn_lotus)
(monster thrashing_horror)
(monster tiamat)
(monster titan)
(monster toadstool)
(monster toenail_golem)
(monster tormentor)
(monster torpor_snail)
(monster torturous_demonspawn)
(monster training_dummy)
(monster troll)
(monster troll_(monster))
(monster twister)
(monster two-headed_ogre)
(monster tyrant_leech)
(monster tzitzimitl)
(monster ufetubus)
(monster ugly_thing)
(monster unborn)
(monster unborn_deep_dwarf)
(monster unseen_horror)
(monster urug)
(monster ushabti)
(monster vampire_(monster))
(monster vampire_bat)
(monster vampire_knight)
(monster vampire_mage)
(monster vampire_mosquito)
(monster vapour)
(monster vashnia)
(monster vault_guard)
(monster vault_sentinel)
(monster vault_warden)
(monster very_ugly_thing)
(monster vine_stalker_(monster))
(monster viper)
(monster wandering_mushroom)
(monster war_dog)
(monster war_gargoyle)
(monster warg)
(monster warmonger)
(monster wasp)
(monster water_elemental)
(monster water_moccasin)
(monster water_nymph)
(monster white_draconian)
(monster white_imp)
(monster wight)
(monster wiglaf)
(monster will-o-the-wisp)
(monster wind_drake)
(monster wizard_(monster))
(monster wizard_statue)
(monster wolf)
(monster wolf_spider)
(monster wood_golem)
(monster worker_ant)
(monster worldbinder)
(monster worm)
(monster wraith)
(monster wretched_star)
(monster wyvern)
(monster xtahua)
(monster yak)
(monster yaktaur)
(monster yaktaur_captain)
(monster yellow_draconian)
(monster ynoxinul)
(monster zombie)
(monster zot_statue)


;;; status effects
(status_effect agile)
(status_effect antimagic)
(status_effect augmentation)
(status_effect bad_forms)
(status_effect berserk)
(status_effect black_mark)
(status_effect blind)
(status_effect brilliant)
(status_effect charm)
(status_effect confusing_touch)
(status_effect confusion)
(status_effect constriction)
(status_effect cooldowns)
(status_effect corona)
(status_effect corrosion)
(status_effect darkness)
(status_effect dazed)
(status_effect death_channel)
(status_effect death's_door)
(status_effect deflect_missiles)
(status_effect disjunction)
(status_effect divine_protection)
(status_effect divine_shield)
(status_effect doom_howl)
(status_effect drain)
(status_effect engorged)
(status_effect engulf)
(status_effect fast+slow)
(status_effect fear)
(status_effect finesse)
(status_effect fire_vulnerable)
(status_effect flayed)
(status_effect flight)
(status_effect frozen)
(status_effect haste)
(status_effect heavenly_storm)
(status_effect held)
(status_effect heroism)
(status_effect horrified)
(status_effect inner_flame)
(status_effect invisibility)
(status_effect lava)
(status_effect leda's_liquefaction)
(status_effect leda's_liquefaction)
(status_effect magic_contamination)
(status_effect mark)
(status_effect mesmerised)
(status_effect might)
(status_effect mirror_damage)
(status_effect no_potions)
(status_effect no_scrolls)
(status_effect olgreb's_toxic_radiance)
(status_effect orb)
(status_effect ozocubu's_armour)
(status_effect paralysis)
(status_effect petrifying/petrified)
(status_effect poison)
(status_effect powered_by_death)
(status_effect quad_damage)
(status_effect recall)
(status_effect regenerating)
(status_effect repel_missiles)
(status_effect resistance)
(status_effect ring_of_flames)
(status_effect sapped_magic)
(status_effect scrying)
(status_effect searing_ray)
(status_effect serpent's_lash)
(status_effect shroud_of_golubria)
(status_effect sickness)
(status_effect silence)
(status_effect silence)
(status_effect sleep)
(status_effect slimify)
(status_effect slow)
(status_effect sluggish)
(status_effect starving)
(status_effect stat_zero)
(status_effect sticky_flame)
(status_effect still_winds)
(status_effect swiftness)
(status_effect teleport)
(status_effect teleport_prevention)
(status_effect tornado)
(status_effect transmutations)
(status_effect umbra)
(status_effect vitalisation)
(status_effect vulnerable)
(status_effect water)
(status_effect weak)

;;; mutations
(mutation acute_vision)
(mutation antennae)
(mutation beak)
(mutation big_wings)
(mutation blink)
(mutation camouflage)
(mutation clarity)
(mutation claws)
(mutation cold_resistance)
(mutation electricity_resistance)
(mutation evolution)
(mutation fangs)
(mutation fire_resistance)
(mutation high_mp)
(mutation hooves)
(mutation horns)
(mutation icy_blue_scales)
(mutation improved_attributes)
(mutation iridescent_scales)
(mutation large_bone_plates)
(mutation magic_resistance)
(mutation molten_scales)
(mutation mutation_resistance)
(mutation passive_mapping)
(mutation poison_breath)
(mutation poison_resistance)
(mutation regeneration)
(mutation repulsion_field)
(mutation robust)
(mutation rugged_brown_scales)
(mutation shaggy_fur)
(mutation slimy_green_scales)
(mutation stinger)
(mutation strong_legs)
(mutation talons)
(mutation tentacle_spike)
(mutation thin_metallic_scales)
(mutation thin_skeletal_structure)
(mutation tough_skin)
(mutation wild_magic)
(mutation yellow_scales)

;;; gods
(god ashenzari)
(god beogh)
(god cheibriados)
(god dithmenos)
(god elyvilon)
(god fedhas)
(god gozag)
(god hepliaklqana)
(god jiyva)
(god kikubaaqudgha)
(god lugonu)
(god makhleb)
(god nemelex)
(god okawaru)
(god qazlal)
(god ru)
(god sif)
(god trog)
(god uskayaw)
(god vehumet)
(god wu_jian)
(god xom)
(god yredelemnul)
(god zin)
(god shining_one)

; used for unknown altars
(god unknown)

;;; potions
(potion ambrosia)
(potion berserkrage)
(potion brilliance)
(potion cancellation)
(potion curing)
(potion degeneration)
(potion experience)
(potion flight)
(potion haste)
(potion healwounds)
(potion invisibility)
(potion lignification)
(potion magic)
(potion might)
(potion mutation)
(potion resistance)
(potion stabbing)

;;; scrolls
(scroll acquirement)
(scroll amnesia)
(scroll blinking)
(scroll brandweapon)
(scroll enchantarmour)
(scroll enchantweapon)
(scroll fear)
(scroll fog)
(scroll holyword)
(scroll identity)
(scroll immolation)
(scroll magicmapping)
(scroll noise)
(scroll randomuselessness)
(scroll removecurse)
(scroll silence)
(scroll summoning)
(scroll teleportation)
(scroll torment)
(scroll vulnerability)

;;; spells
(non_target_based_spell alistairs_intoxication)
(non_target_based_spell animate_dead)
(non_target_based_spell animate_skeleton)
(non_target_based_spell aura_of_abjuration)
(non_target_based_spell beastly_appendage)
(non_target_based_spell blade_hands)
(non_target_based_spell blink)
(non_target_based_spell borgnjors_revivification)
(non_target_based_spell call_canine_familiar)
(non_target_based_spell call_imp)
(non_target_based_spell chain_lightning)
(non_target_based_spell confusing_touch)
(non_target_based_spell conjure_ball_lightning)
(non_target_based_spell conjure_flame)
(non_target_based_spell controlled_blink)
(non_target_based_spell corpse_rot)
(non_target_based_spell death_channel)
(non_target_based_spell deaths_door)
(non_target_based_spell discord)
(non_target_based_spell disjunction)
(non_target_based_spell dragon_form)
(non_target_based_spell dragons_call)
(non_target_based_spell eringyas_noxious_bog)
(non_target_based_spell excruciating_wounds)
(non_target_based_spell foxfire)
(non_target_based_spell hydra_form)
(non_target_based_spell ice_form)
(non_target_based_spell ignite_poison)
(non_target_based_spell ignition)
(non_target_based_spell infusion)
(non_target_based_spell iskenderuns_battlesphere)
(non_target_based_spell ledas_liquefaction)
(non_target_based_spell malign_gateway)
(non_target_based_spell metabolic_englaciation)
(non_target_based_spell monstrous_menagerie)
(non_target_based_spell necromutation)
(non_target_based_spell olgrebs_toxic_radiance)
(non_target_based_spell ozocubus_armour)
(non_target_based_spell ozocubus_refrigeration)
(non_target_based_spell portal_projectile)
(non_target_based_spell recall)
(non_target_based_spell ring_of_flames)
(non_target_based_spell shadow_creatures)
(non_target_based_spell shatter)
(non_target_based_spell shroud_of_golubria)
(non_target_based_spell silence)
(non_target_based_spell simulacrum)
(non_target_based_spell song_of_slaying)
(non_target_based_spell spectral_weapon)
(non_target_based_spell spellforged_servitor)
(non_target_based_spell spider_form)
(non_target_based_spell statue_form)
(non_target_based_spell sticks_to_snakes)
(non_target_based_spell sublimation_of_blood)
(non_target_based_spell summon_demon)
(non_target_based_spell summon_forest)
(non_target_based_spell summon_greater_demon)
(non_target_based_spell summon_guardian_golem)
(non_target_based_spell summon_horrible_things)
(non_target_based_spell summon_hydra)
(non_target_based_spell summon_ice_beast)
(non_target_based_spell summon_mana_viper)
(non_target_based_spell summon_small_mammal)
(non_target_based_spell swiftness)
(target_based_spell absolute_zero)
(target_based_spell agony)
(target_based_spell airstrike)
(target_based_spell apportation)
(target_based_spell bolt_of_magma)
(target_based_spell borgnjors_vile_clutch)
(target_based_spell cause_fear)
(target_based_spell corona)
(target_based_spell dazzling_flash)
(target_based_spell dispel_undead)
(target_based_spell dispersal)
(target_based_spell ensorcelled_hibernation)
(target_based_spell fire_storm)
(target_based_spell fireball)
(target_based_spell freeze)
(target_based_spell freezing_cloud)
(target_based_spell frozen_ramparts)
(target_based_spell fulminant_prism)
(target_based_spell gells_gravitas)
(target_based_spell hailstorm)
(target_based_spell haunt)
(target_based_spell infestation)
(target_based_spell inner_flame)
(target_based_spell invisibility)
(target_based_spell iron_shot)
(target_based_spell irradiate)
(target_based_spell iskenderuns_mystic_blast)
(target_based_spell lees_rapid_deconstruction)
(target_based_spell lehudibs_crystal_spear)
(target_based_spell lesser_beckoning)
(target_based_spell lightning_bolt)
(target_based_spell magic_dart)
(target_based_spell mephitic_cloud)
(target_based_spell orb_of_destruction)
(target_based_spell pain)
(target_based_spell passage_of_golubria)
(target_based_spell passwall)
(target_based_spell petrify)
(target_based_spell poisonous_vapours)
(target_based_spell sandblast)
(target_based_spell searing_ray)
(target_based_spell shock)
(target_based_spell slow)
(target_based_spell starburst)
(target_based_spell static_discharge)
(target_based_spell sticky_flame)
(target_based_spell sting)
(target_based_spell stone_arrow)
(target_based_spell summon_lightning_spire)
(target_based_spell teleport_other)
(target_based_spell tornado)
(target_based_spell tukimas_dance)
(target_based_spell vampiric_draining)
(target_based_spell yaras_violent_unravelling)

;;; skills
(skill fighting)
(skill long_blades)
(skill short_blades)
(skill axes)
(skill maces_&_flails)
(skill polearms)
(skill staves)
(skill unarmed_combat)
(skill bows)
(skill crossbows)
(skill throwing)
(skill slings)
(skill armour)
(skill dodging)
(skill shields)
(skill spellcasting)
(skill conjurations)
(skill hexes)
(skill charms)
(skill summonings)
(skill necromancy)
(skill translocations)
(skill transmutation)
(skill fire_magic)
(skill ice_magic)
(skill air_magic)
(skill earth_magic)
(skill poison_magic)
(skill invocations)
(skill evocations)
(skill stealth)

;;; abilities
(non_target_ability apocalypse)
(non_target_ability banish_self)
(non_target_ability bat_form)
(non_target_ability bend_space)
(non_target_ability bend_time)
(non_target_ability berserk)
(non_target_ability blink)
(non_target_ability briar_patch)
(non_target_ability bribe_branch)
(non_target_ability brothers_in_arms)
(non_target_ability call_merchant)
(non_target_ability channel_magic)
(non_target_ability cleansing_flame)
(non_target_ability corrupt)
(non_target_ability cure_bad_mutations)
(non_target_ability depart_abyss)
(non_target_ability disaster_area)
(non_target_ability divine_protection)
(non_target_ability divine_shield)
(non_target_ability divine_vigour)
(non_target_ability drain_life)
(non_target_ability draw_out_power)
(non_target_ability elemental_force)
(non_target_ability finesse)
(non_target_ability flight)
(non_target_ability gain_random_mutations)
(non_target_ability greater_healing)
(non_target_ability grow_ballistomycete)
(non_target_ability grow_oklob_plant)
(non_target_ability heal_wounds)
(non_target_ability heavenly_storm)
(non_target_ability heroism)
(non_target_ability idealise)
(non_target_ability lesser_healing)
(non_target_ability purification)
(non_target_ability recall)
(non_target_ability recall_undead_slaves)
(non_target_ability receive_corpses)
(non_target_ability receive_necronomicon)
(non_target_ability recite)
(non_target_ability request_jelly)
(non_target_ability resurrection)
(non_target_ability sanctuary)
(non_target_ability scrying)
(non_target_ability serpents_lash)
(non_target_ability shadow_form)
(non_target_ability slimify)
(non_target_ability slouch)
(non_target_ability step_from_time)
(non_target_ability stomp)
(non_target_ability summon_divine_warrior)
(non_target_ability summon_greater_servant)
(non_target_ability summon_lesser_servant)
(non_target_ability temporal_distortion)
(non_target_ability toggle_divine_energy)
(non_target_ability toggle_injury_mirror)
(non_target_ability torment)
(non_target_ability trogs_hand)
(non_target_ability vitalisation)
(non_target_ability wall_jump)
(target_ability_location animate_dead)
(target_ability_location animate_remains)
(target_ability_location banish)
(target_ability_location controlled_blink)
(target_ability_location enslave_soul)
(target_ability_location give_item_to_follower)
(target_ability_location grand_finale)
(target_ability_location heal_other)
(target_ability_location hop)
(target_ability_location Imprison)
(target_ability_location line_pass)
(target_ability_location major_destruction)
(target_ability_location minor_destruction)
(target_ability_location overgrow)
(target_ability_location power_leap)
(target_ability_location rolling_charge)
(target_ability_location shadow_step)
(target_ability_location smite)
(target_ability_location spit_poison)
(target_ability_location transference)
(target_ability_location upheaval)
(target_ability_menu ancestor_identity)
(target_ability_menu ancestor_life)
(target_ability_menu brand_weapon_with_holy)
(target_ability_menu brand_weapon_with_pain)
(target_ability_menu corrupt_weapon)
(target_ability_menu curse_item)
(target_ability_menu deal_four)
(target_ability_menu forget_spell)
(target_ability_menu pick_a_card_any_card)
(target_ability_menu stack_five)
(target_ability_menu transfer_knowledge)
(target_ability_menu triple_draw)
(target_ability_text_message potion_petition)

;;; dungeon locations
(place dungeon_1)
(place dungeon_2)
(place dungeon_3)
(place dungeon_4)
(place dungeon_5)
(place dungeon_6)
(place dungeon_7)
(place dungeon_8)
(place dungeon_9)
(place dungeon_10)
(place dungeon_11)
(place dungeon_12)
(place dungeon_13)
(place dungeon_14)
(place dungeon_15)

(place lair_1)
(place lair_2)
(place lair_3)
(place lair_4)
(place lair_5)
(place lair_6)

(place swamp_1)
(place swamp_2)
(place swamp_3)
(place swamp_4)

(place shoals_1)
(place shoals_2)
(place shoals_3)
(place shoals_4)

(place snake_pit_1)
(place snake_pit_2)
(place snake_pit_3)
(place snake_pit_4)

(place spiders_nest_1)
(place spiders_nest_2)
(place spiders_nest_3)
(place spiders_nest_4)

(place slime_pits_1)
(place slime_pits_2)
(place slime_pits_3)
(place slime_pits_4)
(place slime_pits_5)

(place orcish_mines_1)
(place orcish_mines_2)

(place elven_halls_1)
(place elven_halls_2)
(place elven_halls_3)

(place vaults_1)
(place vaults_2)
(place vaults_3)
(place vaults_4)
(place vaults_5)

(place crypt_1)
(place crypt_2)
(place crypt_3)

(place tomb_1)
(place tomb_2)
(place tomb_3)

(place depths_1)
(place depths_2)
(place depths_3)
(place depths_4)
(place depths_5)

(place abyss_1)
(place abyss_2)
(place abyss_3)
(place abyss_4)
(place abyss_5)

(place cocytus_1)
(place cocytus_2)
(place cocytus_3)
(place cocytus_4)
(place cocytus_5)
(place cocytus_6)
(place cocytus_7)

(place gehenna_1)
(place gehenna_2)
(place gehenna_3)
(place gehenna_4)
(place gehenna_5)
(place gehenna_6)
(place gehenna_7)

(place tartarus_1)
(place tartarus_2)
(place tartarus_3)
(place tartarus_4)
(place tartarus_5)
(place tartarus_6)
(place tartarus_7)

(place iron_city_of_dis_1)
(place iron_city_of_dis_2)
(place iron_city_of_dis_3)
(place iron_city_of_dis_4)
(place iron_city_of_dis_5)
(place iron_city_of_dis_6)
(place iron_city_of_dis_7)

(place zot_1)
(place zot_2)
(place zot_3)
(place zot_4)
(place zot_5)

(connected dungeon_1 dungeon_2)
(connected dungeon_2 dungeon_3)
(connected dungeon_3 dungeon_4)
(connected dungeon_4 dungeon_5)
(connected dungeon_5 dungeon_6)
(connected dungeon_6 dungeon_7)
(connected dungeon_7 dungeon_8)
(connected dungeon_8 dungeon_9)
(connected dungeon_9 dungeon_10)
(connected dungeon_10 dungeon11)
(connected dungeon_11 dungeon12)
(connected dungeon_12 dungeon13)
(connected dungeon_13 dungeon14)
(connected dungeon_14 dungeon15)

(connected lair_1 lair_2)
(connected lair_2 lair_3)
(connected lair_3 lair_4)
(connected lair_4 lair_5)
(connected lair_5 lair_6)

(connected swamp_1 swamp_2)
(connected swamp_2 swamp_3)
(connected swamp_3 swamp_4)

(connected shoals_1 shoals_2)
(connected shoals_2 shoals_3)
(connected shoals_3 shoals_4)

(connected snake_pit_1 snake_pit_2)
(connected snake_pit_2 snake_pit_3)
(connected snake_pit_3 snake_pit_4)

(connected spiders_nest_1 spiders_nest_2)
(connected spiders_nest_2 spiders_nest_3)
(connected spiders_nest_3 spiders_nest_4)

(connected slime_pits_1 slime_pits_2)
(connected slime_pits_2 slime_pits_3)
(connected slime_pits_3 slime_pits_4)
(connected slime_pits_4 slime_pits_5)

(connected orcish_mines_1 orcish_mines_2)

(connected elven_halls_1 elven_halls_2)
(connected elven_halls_2 elven_halls_3)

(connected vaults_1 vaults_2)
(connected vaults_2 vaults_3)
(connected vaults_3 vaults_4)
(connected vaults_4 vaults_5)

(connected crypt_1 crypt_2)
(connected crypt_2 crypt_3)

(connected tomb_1 tomb_2)
(connected tomb_2 tomb_3)

(connected depths_1 depths_2)
(connected depths_2 depths_3)
(connected depths_3 depths_4)
(connected depths_4 depths_5)

(connected abyss_1 abyss_2)
(connected abyss_2 abyss_3)
(connected abyss_3 abyss_4)
(connected abyss_4 abyss_5)

(connected cocytus_1 cocytus_2)
(connected cocytus_2 cocytus_3)
(connected cocytus_3 cocytus_4)
(connected cocytus_4 cocytus_5)
(connected cocytus_5 cocytus_6)
(connected cocytus_6 cocytus_7)

(connected gehenna_1 gehenna_2)
(connected gehenna_2 gehenna_3)
(connected gehenna_3 gehenna_4)
(connected gehenna_4 gehenna_5)
(connected gehenna_5 gehenna_6)
(connected gehenna_6 gehenna_7)

(connected tartarus_1 tartarus_2)
(connected tartarus_2 tartarus_3)
(connected tartarus_3 tartarus_4)
(connected tartarus_4 tartarus_5)
(connected tartarus_5 tartarus_6)
(connected tartarus_6 tartarus_7)

(connected iron_city_of_dis_1 iron_city_of_dis_2)
(connected iron_city_of_dis_2 iron_city_of_dis_3)
(connected iron_city_of_dis_3 iron_city_of_dis_4)
(connected iron_city_of_dis_4 iron_city_of_dis_5)
(connected iron_city_of_dis_5 iron_city_of_dis_6)
(connected iron_city_of_dis_6 iron_city_of_dis_7)

(connected zot_1 zot_2)
(connected zot_2 zot_3)
(connected zot_3 zot_4)
(connected zot_4 zot_5)
