;; This file contains all of the general pddl facts that don't differ between game states

(hungerlevel fainting)
(hungerlevel starving)
(hungerlevel nearstarving)
(hungerlevel veryhungry)
(hungerlevel hungry)
(hungerlevel full)
(hungerlevel veryfull)
(hungerlevel engorged)

(place dungeon_1)
(place dungeon_2)
(place dungeon_3)
(place dungeon_4)
(place dungeon_5)
(place dungeon_6)
(place dungeon_7)
(place dungeon_8)
(place dungeon_9)
(place dungeon_10)
(place dungeon_11)
(place dungeon_12)
(place dungeon_13)
(place dungeon_14)
(place dungeon_15)

(place lair_1)
(place lair_2)
(place lair_3)
(place lair_4)
(place lair_5)
(place lair_6)

(place swamp_1)
(place swamp_2)
(place swamp_3)
(place swamp_4)

(place shoals_1)
(place shoals_2)
(place shoals_3)
(place shoals_4)

(place snake_pit_1)
(place snake_pit_2)
(place snake_pit_3)
(place snake_pit_4)

(place spiders_nest_1)
(place spiders_nest_2)
(place spiders_nest_3)
(place spiders_nest_4)

(place slime_pits_1)
(place slime_pits_2)
(place slime_pits_3)
(place slime_pits_4)
(place slime_pits_5)

(place orcish_mines_1)
(place orcish_mines_2)

(place elven_halls_1)
(place elven_halls_2)
(place elven_halls_3)

(place vaults_1)
(place vaults_2)
(place vaults_3)
(place vaults_4)
(place vaults_5)

(place crypt_1)
(place crypt_2)
(place crypt_3)

(place tomb_1)
(place tomb_2)
(place tomb_3)

(place depths_1)
(place depths_2)
(place depths_3)
(place depths_4)
(place depths_5)

(place abyss_1)
(place abyss_2)
(place abyss_3)
(place abyss_4)
(place abyss_5)

(place cocytus_1)
(place cocytus_2)
(place cocytus_3)
(place cocytus_4)
(place cocytus_5)
(place cocytus_6)
(place cocytus_7)

(place gehenna_1)
(place gehenna_2)
(place gehenna_3)
(place gehenna_4)
(place gehenna_5)
(place gehenna_6)
(place gehenna_7)

(place tartarus_1)
(place tartarus_2)
(place tartarus_3)
(place tartarus_4)
(place tartarus_5)
(place tartarus_6)
(place tartarus_7)

(place iron_city_of_dis_1)
(place iron_city_of_dis_2)
(place iron_city_of_dis_3)
(place iron_city_of_dis_4)
(place iron_city_of_dis_5)
(place iron_city_of_dis_6)
(place iron_city_of_dis_7)

(place zot_1)
(place zot_2)
(place zot_3)
(place zot_4)
(place zot_5)

(connected dungeon_1 dungeon_2)
(connected dungeon_2 dungeon_3)
(connected dungeon_3 dungeon_4)
(connected dungeon_4 dungeon_5)
(connected dungeon_5 dungeon_6)
(connected dungeon_6 dungeon_7)
(connected dungeon_7 dungeon_8)
(connected dungeon_8 dungeon_9)
(connected dungeon_9 dungeon_10)
(connected dungeon_10 dungeon11)
(connected dungeon_11 dungeon12)
(connected dungeon_12 dungeon13)
(connected dungeon_13 dungeon14)
(connected dungeon_14 dungeon15)

(connected lair_1 lair_2)
(connected lair_2 lair_3)
(connected lair_3 lair_4)
(connected lair_4 lair_5)
(connected lair_5 lair_6)

(connected swamp_1 swamp_2)
(connected swamp_2 swamp_3)
(connected swamp_3 swamp_4)

(connected shoals_1 shoals_2)
(connected shoals_2 shoals_3)
(connected shoals_3 shoals_4)

(connected snake_pit_1 snake_pit_2)
(connected snake_pit_2 snake_pit_3)
(connected snake_pit_3 snake_pit_4)

(connected spiders_nest_1 spiders_nest_2)
(connected spiders_nest_2 spiders_nest_3)
(connected spiders_nest_3 spiders_nest_4)

(connected slime_pits_1 slime_pits_2)
(connected slime_pits_2 slime_pits_3)
(connected slime_pits_3 slime_pits_4)
(connected slime_pits_4 slime_pits_5)

(connected orcish_mines_1 orcish_mines_2)

(connected elven_halls_1 elven_halls_2)
(connected elven_halls_2 elven_halls_3)

(connected vaults_1 vaults_2)
(connected vaults_2 vaults_3)
(connected vaults_3 vaults_4)
(connected vaults_4 vaults_5)

(connected crypt_1 crypt_2)
(connected crypt_2 crypt_3)

(connected tomb_1 tomb_2)
(connected tomb_2 tomb_3)

(connected depths_1 depths_2)
(connected depths_2 depths_3)
(connected depths_3 depths_4)
(connected depths_4 depths_5)

(connected abyss_1 abyss_2)
(connected abyss_2 abyss_3)
(connected abyss_3 abyss_4)
(connected abyss_4 abyss_5)

(connected cocytus_1 cocytus_2)
(connected cocytus_2 cocytus_3)
(connected cocytus_3 cocytus_4)
(connected cocytus_4 cocytus_5)
(connected cocytus_5 cocytus_6)
(connected cocytus_6 cocytus_7)

(connected gehenna_1 gehenna_2)
(connected gehenna_2 gehenna_3)
(connected gehenna_3 gehenna_4)
(connected gehenna_4 gehenna_5)
(connected gehenna_5 gehenna_6)
(connected gehenna_6 gehenna_7)

(connected tartarus_1 tartarus_2)
(connected tartarus_2 tartarus_3)
(connected tartarus_3 tartarus_4)
(connected tartarus_4 tartarus_5)
(connected tartarus_5 tartarus_6)
(connected tartarus_6 tartarus_7)

(connected iron_city_of_dis_1 iron_city_of_dis_2)
(connected iron_city_of_dis_2 iron_city_of_dis_3)
(connected iron_city_of_dis_3 iron_city_of_dis_4)
(connected iron_city_of_dis_4 iron_city_of_dis_5)
(connected iron_city_of_dis_5 iron_city_of_dis_6)
(connected iron_city_of_dis_6 iron_city_of_dis_7)

(connected zot_1 zot_2)
(connected zot_2 zot_3)
(connected zot_3 zot_4)
(connected zot_4 zot_5)
